# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
## general purpose linting and formatting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
  - id: validate-pyproject
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.6
  hooks:
  - id: ruff-check
    types_or: [ python, pyi ]
    args: [--fix]
  - id: ruff-format
    types_or: [ python, pyi ]
- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.16.6
  hooks:
  - id: cython-lint
  - id: double-quote-cython-strings
