[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "cython",
    "scipy",
    "numpy",
    "pandas"
]
build-backend = "setuptools.build_meta"

[project]
name = "karyohmm"
version = "0.1.8b"
